name: Generate Snake Animation

on:
  schedule: # Her gece otomatik çalışır
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # Node.js 24'e geçiş için

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # Güncel sürüm

      - name: Generate Snake SVG
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: kaanaltay-hub
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
